// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/tedewaard/folio/src/models"

func HomePage(workProjects []models.Project, sideProjects []models.Project, timeline []models.TimelineItem) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"min-h-screen bg-gray-50\"><!-- Hero/About Section --><section id=\"about\" class=\"flex items-center justify-center bg-white px-4 pt-40 pb-20\"><div class=\"max-w-3xl mx-auto\"><div class=\"flex flex-col items-center mb-8\"><img src=\"/static/images/headshot.jpg\" alt=\"Trevor Edewaard\" class=\"w-32 h-32 rounded-full object-cover object-top mb-6 shadow-lg\"><h1 class=\"text-4xl font-mono font-bold text-gray-900 mb-2\">Trevor Edewaard</h1><p class=\"text-lg text-gray-600 font-mono\">Infrastructure Automation Engineer</p></div><div class=\"space-y-4 text-gray-700 leading-relaxed\"><p>I'm an infrastructure engineer focused on building resilient, automated systems at scale. Currently architecting Kubernetes platforms, implementing GitOps workflows, and automating infrastructure with Terraform and Ansible.</p><p>My work includes designing on-premises Kubernetes infrastructure that reduced disaster recovery time by over 90%, managing 12,000+ global endpoints, and establishing Infrastructure as Code practices across VM provisioning, network automation, and cloud resources.</p><p>I've led major migrations—moving 1,000+ endpoints to Microsoft Intune, consolidating 50 cloud apps to Entra SSO, and retiring legacy systems that had been in place for 20 years. I also spoke at Tanium Converge 2023 and build tooling in Rust, Go, and PowerShell to solve real business problems.</p></div></div></section><!-- Work Projects Section --><section id=\"work-projects\" class=\"py-20 px-4 bg-gray-50\"><div class=\"max-w-6xl mx-auto\"><h2 class=\"text-4xl font-bold text-gray-900 mb-4 text-center\">Work Projects & Accomplishments</h2><p class=\"text-gray-600 text-center mb-12\">Professional achievements and contributions</p><div class=\"grid md:grid-cols-2 lg:grid-cols-3 gap-8\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, project := range workProjects {
				templ_7745c5c3_Err = ProjectCard(project).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></div></section><!-- Side Projects Section --><section id=\"side-projects\" class=\"py-20 px-4 bg-white\"><div class=\"max-w-6xl mx-auto\"><h2 class=\"text-4xl font-bold text-gray-900 mb-4 text-center\">Side Projects</h2><p class=\"text-gray-600 text-center mb-12\">Personal projects and experiments</p><div class=\"grid md:grid-cols-2 lg:grid-cols-3 gap-8\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, project := range sideProjects {
				templ_7745c5c3_Err = ProjectCard(project).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></div></section><!-- Timeline Section --><section id=\"timeline\" class=\"py-20 px-4 bg-gray-50\"><div class=\"max-w-6xl mx-auto mb-12\"><h2 class=\"text-4xl font-bold text-gray-900 mb-4 text-center\">My Journey</h2><p class=\"text-gray-600 text-center\">Career milestones and experiences that shaped my path</p></div><div class=\"relative max-w-6xl mx-auto px-4\"><!-- Center line --><div class=\"absolute left-4 md:left-1/2 transform md:-translate-x-1/2 w-1 bg-gray-300 h-full\"></div><!-- Timeline items --><div class=\"relative\"><div class=\"h-20\"></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for index, item := range timeline {
				templ_7745c5c3_Err = TimelineCard(item, index).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"h-20\"></div></div></div></section></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Base("Trevor Edewaard - Infrastructure Automation Engineer").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
