// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Footer from "./Footer.res.mjs";
import * as Header from "./Header.res.mjs";
import ViteSvg from "./assets/vite.svg";
import * as JsxRuntime from "react/jsx-runtime";
import RescriptLogoSvg from "./assets/rescript-logo.svg";

function App(props) {
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx(Header.make, {}),
      JsxRuntime.jsx("main", {
        children: "Testing",
        className: ""
      }),
      JsxRuntime.jsx(Footer.make, {})
    ],
    className: "w-screen h-screen"
  });
}

let make = App;

export {
  make,
}
/*  Not a pure module */
