// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Header(props) {
  return JsxRuntime.jsx("div", {
    children: "Header"
  });
}

let make = Header;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
