// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button from "./Button.res.mjs";
import ViteSvg from "./assets/vite.svg";
import * as JsxRuntime from "react/jsx-runtime";
import RescriptLogoSvg from "./assets/rescript-logo.svg";

let rescript = RescriptLogoSvg;

let vite = ViteSvg;

function App(props) {
  let match = React.useState(() => 0);
  let setCount = match[1];
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("img", {
            className: "h-24",
            alt: "Vite logo",
            src: vite
          }),
          JsxRuntime.jsx("img", {
            className: "h-24",
            alt: "ReScript logo",
            src: rescript
          })
        ],
        className: "flex justify-evenly items-center"
      }),
      JsxRuntime.jsx("h1", {
        children: "Vite + ReScript",
        className: "text-6xl m-16 font-semibold text-center"
      }),
      JsxRuntime.jsx(Button.make, {
        children: `count is ` + match[0].toString(),
        onClick: param => setCount(count => count + 1 | 0)
      }),
      JsxRuntime.jsxs("p", {
        children: [
          "Edit ",
          JsxRuntime.jsx("code", {
            children: "src/App.res",
            className: "bg-stone-100 font-mono rounded"
          }),
          " and save to test Fast Refresh."
        ],
        className: "my-6 text-center"
      }),
      JsxRuntime.jsxs("p", {
        children: [
          "Learn more about ",
          JsxRuntime.jsxs("a", {
            children: [
              "ReScript",
              "."
            ],
            className: "text-blue-500 hover:underline",
            href: "https://rescript-lang.org/",
            target: "_blank"
          })
        ],
        className: "text-center font-thin text-stone-400"
      })
    ],
    className: "max-w-200"
  });
}

let make = App;

export {
  make,
}
/* rescript Not a pure module */
