/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogTerraformEsxiRouteImport } from './routes/blog/terraform-esxi'
import { Route as BlogIngressNginxRouteImport } from './routes/blog/ingress-nginx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTerraformEsxiRoute = BlogTerraformEsxiRouteImport.update({
  id: '/blog/terraform-esxi',
  path: '/blog/terraform-esxi',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIngressNginxRoute = BlogIngressNginxRouteImport.update({
  id: '/blog/ingress-nginx',
  path: '/blog/ingress-nginx',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog/ingress-nginx': typeof BlogIngressNginxRoute
  '/blog/terraform-esxi': typeof BlogTerraformEsxiRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/ingress-nginx': typeof BlogIngressNginxRoute
  '/blog/terraform-esxi': typeof BlogTerraformEsxiRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog/ingress-nginx': typeof BlogIngressNginxRoute
  '/blog/terraform-esxi': typeof BlogTerraformEsxiRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blog/ingress-nginx' | '/blog/terraform-esxi' | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog/ingress-nginx' | '/blog/terraform-esxi' | '/blog'
  id:
    | '__root__'
    | '/'
    | '/blog/ingress-nginx'
    | '/blog/terraform-esxi'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogIngressNginxRoute: typeof BlogIngressNginxRoute
  BlogTerraformEsxiRoute: typeof BlogTerraformEsxiRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/terraform-esxi': {
      id: '/blog/terraform-esxi'
      path: '/blog/terraform-esxi'
      fullPath: '/blog/terraform-esxi'
      preLoaderRoute: typeof BlogTerraformEsxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/ingress-nginx': {
      id: '/blog/ingress-nginx'
      path: '/blog/ingress-nginx'
      fullPath: '/blog/ingress-nginx'
      preLoaderRoute: typeof BlogIngressNginxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogIngressNginxRoute: BlogIngressNginxRoute,
  BlogTerraformEsxiRoute: BlogTerraformEsxiRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
